name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # trggers when you push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Verify DockerHub Login    
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker info


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myweb:dheeraj

  deploy:
  name: Deploy
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy container on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          echo "Login to DockerHub"
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Pull latest image"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myweb:dheeraj

          echo "Stop old container"
          docker stop flipkart-container || true
          docker rm flipkart-container || true

          echo "Run new container"
          docker run -d \
            --name flipkart-container \
            -p 80:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/myweb:dheeraj
        EOF

